CREATE TABLE library_book ( id varchar(255) NOT NULL,author varchar(255) NOT NULL,genre varchar(255) NOT NULL,name varchar(255) NOT NULL,publish_year int NOT NULL,quantity int NOT NULL,PRIMARY KEY (id));

INSERT INTO library_book (id, name, author, genre, publish_year, quantity) VALUES
-- Technology (25)
(UUID(), 'Clean Code', 'Robert C. Martin', 'Technology', 2008, 5),
(UUID(), 'The Pragmatic Programmer', 'Andrew Hunt', 'Technology', 1999, 3),
(UUID(), 'Design Patterns', 'Erich Gamma', 'Technology', 1994, 4),
(UUID(), 'Effective Java', 'Joshua Bloch', 'Technology', 2018, 6),
(UUID(), 'Java Concurrency in Practice', 'Brian Goetz', 'Technology', 2006, 2),
(UUID(), 'Spring in Action', 'Craig Walls', 'Technology', 2022, 7),
(UUID(), 'Microservices Patterns', 'Chris Richardson', 'Technology', 2018, 3),
(UUID(), 'Refactoring', 'Martin Fowler', 'Technology', 2018, 4),
(UUID(), 'Head First Java', 'Kathy Sierra', 'Technology', 2005, 8),
(UUID(), 'Introduction to Algorithms', 'Thomas H. Cormen', 'Technology', 2009, 3),
(UUID(), 'The Mythical Man-Month', 'Frederick Brooks', 'Technology', 1975, 2),
(UUID(), 'Code Complete', 'Steve McConnell', 'Technology', 2004, 5),
(UUID(), 'You Don''t Know JS', 'Kyle Simpson', 'Technology', 2015, 6),
(UUID(), 'Cracking the Coding Interview', 'Gayle Laakmann McDowell', 'Technology', 2015, 10),
(UUID(), 'The Art of Computer Programming', 'Donald Knuth', 'Technology', 1968, 1),
(UUID(), 'Structure and Interpretation of Computer Programs', 'Harold Abelson', 'Technology', 1996, 2),
(UUID(), 'Domain-Driven Design', 'Eric Evans', 'Technology', 2003, 3),
(UUID(), 'Building Microservices', 'Sam Newman', 'Technology', 2021, 5),
(UUID(), 'Kubernetes in Action', 'Marko Luksa', 'Technology', 2018, 4),
(UUID(), 'Docker Deep Dive', 'Nigel Poulton', 'Technology', 2020, 6),
(UUID(), 'System Design Interview', 'Alex Xu', 'Technology', 2020, 9),
(UUID(), 'Learning SQL', 'Alan Beaulieu', 'Technology', 2020, 5),
(UUID(), 'Pro Git', 'Scott Chacon', 'Technology', 2014, 7),
(UUID(), 'Test Driven Development', 'Kent Beck', 'Technology', 2002, 3),
(UUID(), 'Release It!', 'Michael Nygard', 'Technology', 2018, 4),

-- Fiction (25)
(UUID(), 'To Kill a Mockingbird', 'Harper Lee', 'Fiction', 1960, 8),
(UUID(), '1984', 'George Orwell', 'Fiction', 1949, 10),
(UUID(), 'The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction', 1925, 6),
(UUID(), 'Pride and Prejudice', 'Jane Austen', 'Fiction', 1813, 5),
(UUID(), 'The Catcher in the Rye', 'J.D. Salinger', 'Fiction', 1951, 4),
(UUID(), 'Brave New World', 'Aldous Huxley', 'Fiction', 1932, 3),
(UUID(), 'The Alchemist', 'Paulo Coelho', 'Fiction', 1988, 7),
(UUID(), 'One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 'Fiction', 1967, 4),
(UUID(), 'The Lord of the Rings', 'J.R.R. Tolkien', 'Fiction', 1954, 6),
(UUID(), 'Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 'Fiction', 1997, 15),
(UUID(), 'The Hobbit', 'J.R.R. Tolkien', 'Fiction', 1937, 7),
(UUID(), 'Animal Farm', 'George Orwell', 'Fiction', 1945, 9),
(UUID(), 'Crime and Punishment', 'Fyodor Dostoevsky', 'Fiction', 1866, 3),
(UUID(), 'War and Peace', 'Leo Tolstoy', 'Fiction', 1869, 2),
(UUID(), 'The Brothers Karamazov', 'Fyodor Dostoevsky', 'Fiction', 1880, 3),
(UUID(), 'Moby-Dick', 'Herman Melville', 'Fiction', 1851, 2),
(UUID(), 'Jane Eyre', 'Charlotte Bronte', 'Fiction', 1847, 4),
(UUID(), 'Wuthering Heights', 'Emily Bronte', 'Fiction', 1847, 3),
(UUID(), 'Great Expectations', 'Charles Dickens', 'Fiction', 1861, 5),
(UUID(), 'A Tale of Two Cities', 'Charles Dickens', 'Fiction', 1859, 4),
(UUID(), 'The Picture of Dorian Gray', 'Oscar Wilde', 'Fiction', 1890, 3),
(UUID(), 'Frankenstein', 'Mary Shelley', 'Fiction', 1818, 5),
(UUID(), 'Dracula', 'Bram Stoker', 'Fiction', 1897, 4),
(UUID(), 'The Count of Monte Cristo', 'Alexandre Dumas', 'Fiction', 1844, 3),
(UUID(), 'Les Miserables', 'Victor Hugo', 'Fiction', 1862, 2),

-- Science Fiction (15)
(UUID(), 'Dune', 'Frank Herbert', 'Science Fiction', 1965, 3),
(UUID(), 'Foundation', 'Isaac Asimov', 'Science Fiction', 1951, 4),
(UUID(), 'Neuromancer', 'William Gibson', 'Science Fiction', 1984, 3),
(UUID(), 'Ender''s Game', 'Orson Scott Card', 'Science Fiction', 1985, 5),
(UUID(), 'The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 'Science Fiction', 1979, 8),
(UUID(), 'Fahrenheit 451', 'Ray Bradbury', 'Science Fiction', 1953, 6),
(UUID(), 'Snow Crash', 'Neal Stephenson', 'Science Fiction', 1992, 3),
(UUID(), 'The Left Hand of Darkness', 'Ursula K. Le Guin', 'Science Fiction', 1969, 2),
(UUID(), 'Hyperion', 'Dan Simmons', 'Science Fiction', 1989, 3),
(UUID(), 'The Martian', 'Andy Weir', 'Science Fiction', 2011, 10),
(UUID(), 'Project Hail Mary', 'Andy Weir', 'Science Fiction', 2021, 8),
(UUID(), 'Ready Player One', 'Ernest Cline', 'Science Fiction', 2011, 6),
(UUID(), '2001: A Space Odyssey', 'Arthur C. Clarke', 'Science Fiction', 1968, 4),
(UUID(), 'Slaughterhouse-Five', 'Kurt Vonnegut', 'Science Fiction', 1969, 3),
(UUID(), 'Do Androids Dream of Electric Sheep?', 'Philip K. Dick', 'Science Fiction', 1968, 3),

-- Non-Fiction (10)
(UUID(), 'Sapiens', 'Yuval Noah Harari', 'Non-Fiction', 2011, 9),
(UUID(), 'Homo Deus', 'Yuval Noah Harari', 'Non-Fiction', 2015, 6),
(UUID(), 'Educated', 'Tara Westover', 'Non-Fiction', 2018, 7),
(UUID(), 'Becoming', 'Michelle Obama', 'Non-Fiction', 2018, 8),
(UUID(), 'A Brief History of Time', 'Stephen Hawking', 'Non-Fiction', 1988, 5),
(UUID(), 'The Diary of a Young Girl', 'Anne Frank', 'Non-Fiction', 1947, 6),
(UUID(), 'Guns, Germs, and Steel', 'Jared Diamond', 'Non-Fiction', 1997, 3),
(UUID(), 'The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 'Non-Fiction', 2010, 4),
(UUID(), 'Born a Crime', 'Trevor Noah', 'Non-Fiction', 2016, 5),
(UUID(), 'Thinking in Systems', 'Donella Meadows', 'Non-Fiction', 2008, 3),

-- Self-Help (10)
(UUID(), 'Atomic Habits', 'James Clear', 'Self-Help', 2018, 12),
(UUID(), 'Deep Work', 'Cal Newport', 'Self-Help', 2016, 5),
(UUID(), 'The 7 Habits of Highly Effective People', 'Stephen Covey', 'Self-Help', 1989, 6),
(UUID(), 'How to Win Friends and Influence People', 'Dale Carnegie', 'Self-Help', 1936, 7),
(UUID(), 'The Power of Habit', 'Charles Duhigg', 'Self-Help', 2012, 5),
(UUID(), 'Mindset', 'Carol S. Dweck', 'Self-Help', 2006, 4),
(UUID(), 'The Subtle Art of Not Giving a F*ck', 'Mark Manson', 'Self-Help', 2016, 8),
(UUID(), 'Can''t Hurt Me', 'David Goggins', 'Self-Help', 2018, 6),
(UUID(), 'The Four Agreements', 'Don Miguel Ruiz', 'Self-Help', 1997, 4),
(UUID(), 'Man''s Search for Meaning', 'Viktor E. Frankl', 'Self-Help', 1946, 5),

-- Business (8)
(UUID(), 'The Lean Startup', 'Eric Ries', 'Business', 2011, 4),
(UUID(), 'Zero to One', 'Peter Thiel', 'Business', 2014, 5),
(UUID(), 'Good to Great', 'Jim Collins', 'Business', 2001, 3),
(UUID(), 'The Innovator''s Dilemma', 'Clayton Christensen', 'Business', 1997, 4),
(UUID(), 'Start with Why', 'Simon Sinek', 'Business', 2009, 6),
(UUID(), 'Rich Dad Poor Dad', 'Robert Kiyosaki', 'Business', 1997, 9),
(UUID(), 'Think and Grow Rich', 'Napoleon Hill', 'Business', 1937, 5),
(UUID(), 'The Hard Thing About Hard Things', 'Ben Horowitz', 'Business', 2014, 3),

-- Psychology (7)
(UUID(), 'Thinking, Fast and Slow', 'Daniel Kahneman', 'Psychology', 2011, 6),
(UUID(), 'Influence', 'Robert Cialdini', 'Psychology', 1984, 4),
(UUID(), 'Predictably Irrational', 'Dan Ariely', 'Psychology', 2008, 3),
(UUID(), 'The Psychology of Money', 'Morgan Housel', 'Psychology', 2020, 7),
(UUID(), 'Emotional Intelligence', 'Daniel Goleman', 'Psychology', 1995, 4),
(UUID(), 'Flow', 'Mihaly Csikszentmihalyi', 'Psychology', 1990, 3),
(UUID(), 'Quiet', 'Susan Cain', 'Psychology', 2012, 5);
